# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sayzlim.net
title: sayzlim.net
subtitle:
author: Sayz Lim
simple_search: http://google.com/search
description: I write articles on how to organize, minimize, and focus works with Mac.

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%b %d, %Y"

# Social Media Accounts
twitter: "@sayzlim"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feedpress.me/sayzlim
subscribe_email: http://eepurl.com/OGGfD
# RSS feeds can list your email address if you like
email: talk@sayzlim.net

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root:
permalink: /:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: categories
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 5          # Posts per page on the blog index
pagination_dir:  # Directory base for pagination URLs eg. /blog/page/2/
excerpt_link: "Continue Reading"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!--more-->

titlecase: false       # Converts page and post titles to titlecase